name: ci

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: vercel-deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          curl -X POST ${{secrets.VERCEL_DEPLOY_HOOK_URL}}
